sudo: false
dist: bionic
language: generic

env:
  global:
    - GCC=gcc-5
    - GXX=g++-5

cache:
  directories:
    - $HOME/.stack/

addons:
  apt:
    packages:
      - gcc-5
      - g++-5
      - libgmp-dev
    sources:
      - llvm-toolchain-bionic-12
      - ubuntu-toolchain-r-test

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export CC=/usr/bin/$GCC
  - export CXX=/usr/bin/$GXX
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
  - sudo apt-get update
  - sudo apt-get --yes install llvm-12 llvm-12-dev

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps
